-- MySQL Script generated by MySQL Workbench
-- Mon Jan 23 19:34:13 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `candidats`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `candidats` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `candidats` (
  `candidat_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `candidatura_id` INT UNSIGNED NOT NULL,
  `persona_id` INT UNSIGNED NOT NULL,
  `provincia_id` TINYINT UNSIGNED NOT NULL,
  `num_ordre` TINYINT NULL COMMENT 'Num ordre del candidatdins la llista del partit dins de la circumpscripció que es presenta.',
  `tipus` ENUM('T', 'S') NULL COMMENT 'T=Titular, S=Suplent',
  PRIMARY KEY (`candidat_id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `uk_candidats_persona_cand` ON `candidats` (`candidatura_id` ASC, `persona_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `candidatures`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `candidatures` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `candidatures` (
  `candidatura_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `eleccio_id` TINYINT UNSIGNED NOT NULL,
  `codi_candidatura` CHAR(6) NULL,
  `nom_curt` VARCHAR(50) NULL COMMENT 'Sigles de la candidatura',
  `nom_llarg` VARCHAR(150) NULL COMMENT 'Nom llarg de la candidatura (denominació)',
  `codi_acumulacio_provincia` CHAR(6) NULL COMMENT 'Codi de la candidatura d\'acumulació a nivell provincial.',
  `codi_acumulacio_ca` CHAR(6) NULL COMMENT 'Codi de la candidatura d\'acumulació a nivell de comunitat autònoma',
  `codi_acumulario_nacional` CHAR(6) NULL,
  PRIMARY KEY (`candidatura_id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `uk_eleccions_partits` ON `candidatures` (`eleccio_id` ASC, `codi_candidatura` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `comunitats_autonomes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `comunitats_autonomes` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `comunitats_autonomes` (
  `comunitat_aut_id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `codi_ine` CHAR(2) NOT NULL,
  PRIMARY KEY (`comunitat_aut_id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `uk_com_aut_codi_ine` ON `comunitats_autonomes` (`codi_ine` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `eleccions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eleccions` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `eleccions` (
  `eleccio_id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `data` DATE NOT NULL COMMENT 'Data (dia mes i any) de quan s\'han celebrat les eleccions',
  `any` YEAR GENERATED ALWAYS AS (YEAR(data))  COMMENT 'any el qual s\'han celebrat les eleccions',
  `mes` TINYINT GENERATED ALWAYS AS (MONTH(data)) STORED COMMENT 'El mes que s\'han celebrat les eleccions',
  PRIMARY KEY (`eleccio_id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `uk_eleccions_any_mes` ON `eleccions` (`any` ASC, `mes` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `uk_eleccions_data` ON `eleccions` (`data` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `eleccions_municipis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eleccions_municipis` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `eleccions_municipis` (
  `eleccio_id` TINYINT UNSIGNED NOT NULL,
  `municipi_id` SMALLINT UNSIGNED NOT NULL,
  `num_meses` SMALLINT UNSIGNED NULL,
  `cens` INT UNSIGNED NULL,
  `vots_emesos` INT UNSIGNED NULL COMMENT 'Número total de vots realitzats en el municipi',
  `vots_valids` INT UNSIGNED NULL COMMENT 'Número de vots es que tindran en compte: vots a candidatures + vots nuls',
  `vots_candidatures` INT UNSIGNED NULL COMMENT 'Total de vots a les candidatures\n',
  `vots_blanc` INT UNSIGNED NULL,
  `vots_nuls` INT UNSIGNED NULL,
  PRIMARY KEY (`eleccio_id`, `municipi_id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `uk_eleccions_municipis` ON `eleccions_municipis` (`eleccio_id` ASC, `municipi_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `municipis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `municipis` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `municipis` (
  `municipi_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(100) NULL,
  `codi_ine` CHAR(3) NOT NULL,
  `provincia_id` TINYINT UNSIGNED NOT NULL,
  `districte` CHAR(2) NULL COMMENT 'Número de districte municipal , sinó el seu valor serà 99. Per exemple aquí municiís com Blanes el seu valor serà 99, però en ciutats com Barcelona hi haurà el número de districte',
  PRIMARY KEY (`municipi_id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `uk_municipis_codi_ine` ON `municipis` (`codi_ine` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `persones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `persones` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `persones` (
  `persona_id` INT UNSIGNED NOT NULL,
  `nom` VARCHAR(30) NULL,
  `cog1` VARCHAR(30) NULL,
  `cog2` VARCHAR(30) NULL,
  `sexe` ENUM('M', 'F') NULL COMMENT 'M=Masculí, F=Femení',
  `data_naixement` DATE NULL,
  `dni` CHAR(10) NOT NULL,
  PRIMARY KEY (`persona_id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `uk_candidats_dni` ON `persones` (`dni` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `provincies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `provincies` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `provincies` (
  `provincia_id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `comunitat_aut_id` TINYINT UNSIGNED NOT NULL,
  `nom` VARCHAR(45) NULL,
  `codi_ine` CHAR(2) NOT NULL,
  `num_escons` TINYINT UNSIGNED NULL COMMENT 'Numero d\'escons que li pertoquen a aquella provincia',
  PRIMARY KEY (`provincia_id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `uk_provincies_codi_ine` ON `provincies` (`codi_ine` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `vots_candidatures_ca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vots_candidatures_ca` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `vots_candidatures_ca` (
  `comunitat_autonoma_id` TINYINT UNSIGNED NOT NULL,
  `candidatura_id` INT UNSIGNED NOT NULL,
  `vots` INT UNSIGNED NULL,
  PRIMARY KEY (`comunitat_autonoma_id`, `candidatura_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `vots_candidatures_mun`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vots_candidatures_mun` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `vots_candidatures_mun` (
  `eleccio_id` TINYINT UNSIGNED NOT NULL,
  `municipi_id` SMALLINT UNSIGNED NOT NULL,
  `candidatura_id` INT UNSIGNED NOT NULL,
  `vots` INT UNSIGNED NULL COMMENT 'Número de vots obtinguts per la candidatura',
  PRIMARY KEY (`eleccio_id`, `municipi_id`, `candidatura_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `vots_candidatures_prov`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vots_candidatures_prov` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `vots_candidatures_prov` (
  `provincia_id` TINYINT UNSIGNED NOT NULL,
  `candidatura_id` INT UNSIGNED NOT NULL,
  `vots` INT UNSIGNED NULL COMMENT 'Número de vots obtinguts per la candidatura',
  `candidats_obtinguts` SMALLINT UNSIGNED NULL COMMENT 'Número de candidats obtinguts per la candidatura',
  PRIMARY KEY (`provincia_id`, `candidatura_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
